<a href="https://colab.research.google.com/github/jashwanth-cse/Jashwanth-Codeboosters-Internship-2026/blob/main/Phase_01_Data_Engineering/Day_01_Introduction_to_Data_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("student_performance.csv")

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("No.of Rows & Columns:",df.shape)

No.of Rows & Columns: (30, 13)

In [ ]:
print("No.of rows",df.shape[0])

No.of rows 30

In [ ]:
print("No.of columns",df.shape[1])

No.of columns 13

In [ ]:
print(df.columns)

Index(['student_id', 'name', 'age', 'gender', 'department', 'semester',
       'math_score', 'science_score', 'english_score', 'programming_score',
       'attendance_percentage', 'city', 'admission_year'],
      dtype='object')

In [ ]:
print(df.index)

RangeIndex(start=0, stop=30, step=1)

In [ ]:
df

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("Columns in the dataset:")
print(df.columns.tolist())

Columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
print("Missing values in each column")
print(df.isnull().sum())

Missing values in each column
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

1. df.isnull()

Checks every cell and returns:

True → value is missing

2. .sum()

In Python:

True = 1
False = 0

So summing counts the missing values.


False → value exists

In [ ]:
print(df['name'])

0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print(df['department'].unique())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

.unique() returns only the unique values in a column

In [ ]:
print(df['department'].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

Counts how much time each unique value appears

In [ ]:
cs_students=df[df['department']=='Computer Science']

In [ ]:
print(f"Number of computer science students:",{len(cs_students)})

Number of computer science students: {13}

In [ ]:
high_attendance=df[df['attendance_percentage']>90]

In [ ]:
print(f"Students above 90% attendance:",{len(high_attendance)})

Students above 90% attendance: {10}

In [61]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
top_student=df.loc[df['total_score'].idxmax()]

In [ ]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)

In [ ]:
print(dept_avg)

department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:
df_sorted=df.sort_values(by='total_score', ascending=False)

**Practice questions:**


1.   How many students are from Electronics department
2.   What is the average attendace of female students
3. Who is the student with lowest programming score
4. How many students scored above 80 in math
5. What is the average total_score for students with attendance above 90%

In [ ]:
sts_in_els_dept=df[df['department']=='Electronics']
print("Number of students in Electronics department:",end=" ")
print(len(sts_in_els_dept))

Number of students in Electronics department: 6

In [ ]:
#avg_attendance_of_female_students=
female_students=df[df['gender']=="Female"]
average=female_students['attendance_percentage'].mean()
print("Average attendance of female students:",average)

Average attendance of female students: 88.53333333333333

In [ ]:
low=df.loc[df['programming_score'].idxmin()]
student=low['name']
print("student with lowest programming score:",end=" ")
print(student)

student with lowest programming score: Manoj Pandey

In [ ]:
math=df[df['math_score']>80]
print("No. of students scored above 80 in math:",end=" ")
print(len(math))

No. of students scored above 80 in math: 11

In [60]:
attendance=df[df['attendance_percentage']>90]
avg_total=attendance['total_score'].mean()
print("Average total score for students with attendance above 90%:",end=" ")
print(avg_total)

Average total score for students with attendance above 90%: 335.8

# MINI PROJECT : Student Data Explorer
# Objective:

Create a Student Performance Explorer using Pandas and Pythin to analyze student data and generate a detailed report.

# Dataset Columns:

name

gender

department

math_score

programming_score

attendance_percentage

total_score

# Tasks to perform:
1. Display Project title

 Print a formatte title with seperator lines

2. Dataset Overview

Display:

-Total number of students

-total number of columns

-number of unique departments

3. Department wise analysis

display the count of students in each department.

4. Score Analysis

Find and Display:

-highest math score

-lowest math score

-avg math score

-avg programming score

-avg attendance percentage

5. Gender wise Analysis

Calculate and display avg total score by gender

6. Top performers

Display top 5 students based on total score.

Show:

-Student name

-Department

-total score

7. Attendance Analysis

Find students whose attendance is below 75%

Display:

-Name

-Department

-Atendance Percentage

If all students have attendance above 75%, print a suitable message.

# Concepts to use:

-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional Statements, f-strings

In [66]:
print('----------------------------------------------------------')
print('                Student Data Explorer')
print('----------------------------------------------------------')
print('Total Number of Students:',end=" ")
print(len(df))
print("Total Number of Columns:",end=" ")
print(df.shape[1])
print("Number of unique departments:",end=" ")
print(df['department'].nunique())
print("Number of Students per department:",end=" ")
print(df['department'].value_counts())
high_math=df['math_score'].max()
print(f'Highest math score:{high_math}')
low_math=df['math_score'].min()
print(f'Lowest math score:{low_math}')
avg_math=df['math_score'].mean()
print(f'Average math score:{avg_math}')
avg_prog=df['programming_score'].mean()
print(f'Avergae Programming Score:{avg_prog}')
avg_att=df['attendance_percentage'].mean()
print(f'Average Attendance Percentage:{avg_att}')
gender_avg=df.groupby('gender')['total_score'].mean().round(2)
print(f"Average Total Score grouped by gender:{gender_avg}")
df_sorted=df.sort_values(by='total_score',ascending=False)
print("Top 5 students by total score")
print(df_sorted[['name','department','total_score']].head(5))
low_att=df[df['attendance_percentage']<75]
print("Students with low attendance percentage:")
print(low_att[['name','department','attendance_percentage']])

----------------------------------------------------------
                Student Data Explorer
----------------------------------------------------------
Total Number of Students: 30
Total Number of Columns: 14
Number of unique departments: 4
Number of Students per department: department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64
Highest math score:95
Lowest math score:56
Average math score:76.06666666666666
Avergae Programming Score:67.6
Average Attendance Percentage:84.5
Average Total Score grouped by gender:gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64
Top 5 students by total score
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356
Students with low attendance percentage:
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73